---
- name: Install dependencies
  host: _Name_ansible_control_plane_server
  become: True
  tasks:
    - name: Update to latest Yum packages
      ansible.builtin.yum:
        name: '*'
        state: latest
    - name: Install ansible, python3
      ansible.builtin.yum:
        name:
          - ansible
          - python3
          - boto3
        state: present

- name: Copy playbooks and config files
  host: _Name_ansible_control_plane_server
  tasks:
    - name: Install ansible role from galaxy
      community.general.ansible.galaxy_install:
        type: role
        name: geerlingguy.mysql
    - name: Install ansible collection for ec2 module
      community.general.ansible.galaxy_install:
        type: collection
        name: amazon.aws
    - name: Check that .aws dir exists
      file: path=~/.aws state=directory
    - name: Copy aws creds
      ansible.builtin.copy:
        src: ~/.aws/credentials
        dest: /home/ec2-user/.aws/credentials
    - name: Copy private ssh key for app servers
      ansible.builtin.copy:
        src: "{{ ssh_key }}"
        dest: /home/ec2-user
        mode: 0400
    - name: Copy ansible playbook and config files
      ansible.builtin.copy:
        src: ~/PycharmProjects/DevopsBootcamp_AnsibleExercises
        dest: /home/ec2-user
      with_fileglob: ./6-*.yaml
    - name: Copy ansible dynamic inventory file
      src: ~/PycharmProjects/DevopsBootcamp_AnsibleExercises/inventory_aws_ec2.yaml
      dest: /home/ec2-user
    - name: Copy ansible config file
      ansible.builtin.copy:
        src: ~/PycharmProjects/DevopsBootcamp_AnsibleExercises/ansible.cfg
        dest: /home/ec2-user
    - name: Copy java jar file
      ansible.builtin.copy:
        src: ~/PycharmProjects/ansible-exercises/build/libs/bootcamp-java-mysql-project-1.0-SNAPSHOT.jar
        dest: /home/ec2-user
