---
- name: Install dependencies
  host: _Name_ansible_control_plane_server
  become: True
  tasks:
    - name: Update to latest Yum packages
      ansible.builtin.yum:
        name: '*'
        state: latest
    - name: Install ansible, python3
      ansible.builtin.yum:
        name:
          - ansible
          - python3
          - boto3
        state: present

- name: Copy playbooks and config files
  host: _Name_ansible_control_plane_server
  tasks:
    - name: Copy
      ansible.builtin.copy:
        src: ~/PycharmProjects/DevopsBootcamp_AnsibleExercises
        dest: /home/ec2-user
