---
- name: Create ansible server
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create ansible server on EC2
      amazon.aws.ec2_instance:
        key_name: "{{ ssh_key }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: t2.small
        security_group: ansible
        network_interfaces:
          - assign_public_ip: true
        image_id: ami-0fff1b9a61dec8a5f
        wait: true
        state: started
        tags:
          Name: "ansible-control-plane-server"